export type ServiceTierType =
  | "PROSPECT"
  | "WEBSITE_BUILD"
  | "WEBSITE_LIVE"
  | "BRAND_CURATION"
  | "SOCIAL_MEDIA"
  | "ANALYTICS"
  | "CHURNED";

export type TaskStatus = "OPEN" | "IN_PROGRESS" | "DONE" | "SNOOZED" | "CANCELLED";

export type TaskType =
  | "MANUAL"
  | "AUTO_UPSELL_PITCH"
  | "AUTO_CHECK_IN"
  | "AUTO_INVOICE_REMINDER"
  | "AUTO_CONTRACT_RENEWAL"
  | "BUILD_MILESTONE";

export type InteractionType = "CALL" | "EMAIL" | "MEETING" | "TEXT" | "SITE_VISIT" | "OTHER";

export type RetainerStatus = "ACTIVE" | "PAUSED" | "CANCELLED" | "PENDING_FIRST_PAYMENT";

export type UserRole = "SALES" | "TECHNICAL";

export type RuleAnchor = "TIER_CHANGE" | "RETAINER_START" | "RETAINER_END";

export type DealStage = "New" | "Contacted" | "Quoted" | "Won" | "Lost";

export interface User {
  id: string;
  name: string;
  email: string;
  role: UserRole;
}

export interface Contact {
  id: string;
  clientId: string;
  firstName: string;
  lastName: string;
  title: string | null;
  email: string | null;
  phone: string | null;
  isPrimary: boolean;
  createdAt: string;
}

export interface Retainer {
  id: string;
  clientId: string;
  tier: ServiceTierType;
  monthlyAmount: number;
  status: RetainerStatus;
  startDate: string | null;
  endDate: string | null;
  billingDay: number | null;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
  client?: { id: string; businessName: string; isActive: boolean };
}

export interface Task {
  id: string;
  clientId: string | null;
  title: string;
  description: string | null;
  type: TaskType;
  status: TaskStatus;
  dueDate: string | null;
  assignedToId: string | null;
  completedAt: string | null;
  snoozedUntil: string | null;
  createdAt: string;
  autoGenerated: boolean;
  sourceRuleId: string | null;
  client?: { id: string; businessName: string; currentTier: ServiceTierType } | null;
  assignedTo?: { id: string; name: string; role: UserRole } | null;
}

export interface Interaction {
  id: string;
  clientId: string;
  type: InteractionType;
  summary: string;
  occurredAt: string;
  loggedById: string | null;
  loggedBy?: { id: string; name: string } | null;
  client?: { id: string; businessName: string };
}

export interface ServiceHistoryEntry {
  id: string;
  clientId: string;
  fromTier: ServiceTierType | null;
  toTier: ServiceTierType;
  changedAt: string;
  changedById: string | null;
  changedBy?: { id: string; name: string } | null;
  note: string | null;
}

export interface Document {
  id: string;
  clientId: string;
  fileName: string;
  fileUrl: string;
  storageKey: string | null;
  category: string | null;
  uploadedAt: string;
}

export interface ClientListItem {
  id: string;
  businessName: string;
  industry: string | null;
  websiteUrl: string | null;
  currentTier: ServiceTierType;
  accountOwnerId: string | null;
  accountOwner: { id: string; name: string; role: UserRole } | null;
  websiteLaunchDate: string | null;
  logoUrl: string | null;
  isActive: boolean;
  mrr: number;
  lastInteractionAt: string | null;
  nextTask: Task | null;
  primaryContact: Contact | null;
  daysSinceLaunch: number | null;
  isAtRisk: boolean;
  retainers: Retainer[];
}

export interface ClientDetail {
  id: string;
  businessName: string;
  industry: string | null;
  websiteUrl: string | null;
  address: string | null;
  city: string | null;
  state: string | null;
  zip: string | null;
  currentTier: ServiceTierType;
  accountOwnerId: string | null;
  accountOwner: { id: string; name: string; role: UserRole } | null;
  websiteLaunchDate: string | null;
  notes: string | null;
  logoUrl: string | null;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  mrr: number;
  daysSinceLaunch: number | null;
  isAtRisk: boolean;
  contacts: Contact[];
  retainers: Retainer[];
  tasks: Task[];
  interactions: Interaction[];
  serviceHistory: ServiceHistoryEntry[];
  documents: Document[];
}

export interface Deal {
  id: string;
  businessName: string;
  contactName: string | null;
  contactEmail: string | null;
  contactPhone: string | null;
  source: string | null;
  stage: DealStage;
  estimatedValue: number | null;
  notes: string | null;
  clientId: string | null;
  createdAt: string;
  stageChangedAt: string;
  lostReason: string | null;
  client?: { id: string; businessName: string } | null;
}

export interface AutomationRule {
  id: string;
  name: string;
  triggerTier: ServiceTierType | null;
  anchor: RuleAnchor;
  daysAfterTrigger: number;
  repeatEveryDays: number | null;
  requiresActiveRetainer: boolean;
  taskTitleTemplate: string;
  taskType: TaskType;
  isActive: boolean;
  createdAt: string;
  _count?: { generatedTasks: number };
}

export interface MrrTrendPoint {
  month: string;
  mrr: number;
}

export interface DashboardSummary {
  totalMRR: number;
  pendingMRR: number;
  mrrChangeVsLastMonth: number;
  activeClientCount: number;
  clientsByTier: Partial<Record<ServiceTierType, number>>;
  overdueTasks: number;
  tasksThisWeek: number;
  atRiskClients: {
    clientId: string;
    businessName: string;
    daysSinceLaunch: number;
    tier: ServiceTierType;
  }[];
  mrrTrend: MrrTrendPoint[];
  recentActivity: {
    id: string;
    type: InteractionType;
    summary: string;
    occurredAt: string;
    clientId: string;
    businessName: string;
    loggedBy: string | null;
  }[];
}

export interface RevenueSummary {
  retainers: Retainer[];
  totalActiveMRR: number;
  pendingMRR: number;
  lostThisQuarter: number;
  mrrByTier: Partial<Record<ServiceTierType, number>>;
  mrrTrend: MrrTrendPoint[];
}
