import { useMemo, useState, type FormEvent } from "react";
import clsx from "clsx";
import { Plus } from "lucide-react";
import { useAuth } from "../context/AuthContext";
import {
  useCompleteTask,
  useCreateTask,
  useTasks,
  useUpdateTask,
  useUsers,
} from "../hooks/queries";
import type { TaskType } from "../types";
import { TASK_TYPE_LABELS } from "../lib/format";
import { SearchableClientSelect } from "../components/SearchableClientSelect";
import { SlideOverPanel } from "../components/SlideOverPanel";
import { TaskChecklist } from "../components/TaskChecklist";
import { Button, Card, ErrorNotice, Field, Skeleton } from "../components/ui";

type AssigneeFilter = "me" | "all" | string;
type SourceFilter = "all" | "auto" | "manual";

const AUTO_TYPES: TaskType[] = [
  "AUTO_UPSELL_PITCH",
  "AUTO_CHECK_IN",
  "AUTO_INVOICE_REMINDER",
  "AUTO_CONTRACT_RENEWAL",
];

export function Tasks() {
  const { user } = useAuth();
  const { data: users = [] } = useUsers();
  const [assignee, setAssignee] = useState<AssigneeFilter>("me");
  const [showCompleted, setShowCompleted] = useState(false);
  const [source, setSource] = useState<SourceFilter>("all");
  const [creating, setCreating] = useState(false);

  const assignedToId =
    assignee === "me" ? user?.id : assignee === "all" ? undefined : assignee;

  const tasksQuery = useTasks({
    assignedToId,
    includeCompleted: showCompleted || undefined,
  });

  const completeTask = useCompleteTask();
  const updateTask = useUpdateTask();

  const tasks = useMemo(() => {
    const all = tasksQuery.data ?? [];
    if (source === "auto") return all.filter((t) => t.autoGenerated);
    if (source === "manual") return all.filter((t) => !t.autoGenerated);
    return all;
  }, [tasksQuery.data, source]);

  const handleSnooze = (taskId: string) => {
    const snoozedUntil = new Date();
    snoozedUntil.setDate(snoozedUntil.getDate() + 7);
    updateTask.mutate({ id: taskId, data: { snoozedUntil: snoozedUntil.toISOString() } });
  };

  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h1 className="text-xl font-semibold text-slate-900">Tasks</h1>
          <p className="text-sm text-slate-500">
            {tasks.length} {tasks.length === 1 ? "task" : "tasks"} in this view
          </p>
        </div>
        <Button onClick={() => setCreating(true)}>
          <Plus className="h-4 w-4" aria-hidden />
          New Task
        </Button>
      </div>

      <div className="flex flex-wrap items-center gap-x-4 gap-y-2">
        <ToggleGroup
          label="Assignee"
          value={assignee}
          onChange={setAssignee}
          options={[
            { value: "me", label: "Me" },
            ...users.map((u) => ({ value: u.id, label: u.name })),
            { value: "all", label: "Everyone" },
          ]}
        />

        <ToggleGroup
          label="Source"
          value={source}
          onChange={(value) => setSource(value as SourceFilter)}
          options={[
            { value: "all", label: "All" },
            { value: "auto", label: "Automated" },
            { value: "manual", label: "Manual" },
          ]}
        />

        <label className="flex items-center gap-1.5 text-xs text-slate-600">
          <input
            type="checkbox"
            checked={showCompleted}
            onChange={(e) => setShowCompleted(e.target.checked)}
            className="h-3.5 w-3.5 rounded border-slate-300 text-brand-700"
          />
          Show completed
        </label>
      </div>

      {tasksQuery.isError && (
        <ErrorNotice
          message={(tasksQuery.error as Error).message}
          onRetry={() => tasksQuery.refetch()}
        />
      )}

      <Card className="p-5">
        {tasksQuery.isLoading ? (
          <div className="space-y-2">
            {Array.from({ length: 6 }).map((_, i) => (
              <Skeleton key={i} className="h-16" />
            ))}
          </div>
        ) : (
          <TaskChecklist
            tasks={tasks}
            onComplete={(id) => completeTask.mutate(id)}
            onSnooze={handleSnooze}
            emptyTitle="No tasks here"
            emptyDescription="Try widening the assignee filter, or add a task."
          />
        )}
      </Card>

      <NewTaskPanel open={creating} onClose={() => setCreating(false)} />
    </div>
  );
}

function ToggleGroup<T extends string>({
  label,
  value,
  onChange,
  options,
}: {
  label: string;
  value: T;
  onChange: (value: T) => void;
  options: { value: T; label: string }[];
}) {
  return (
    <div className="flex items-center gap-2">
      <span className="text-xs font-medium text-slate-400">{label}</span>
      <div className="flex rounded-lg border border-slate-300 bg-white p-0.5">
        {options.map((option) => (
          <button
            key={option.value}
            type="button"
            onClick={() => onChange(option.value)}
            aria-pressed={value === option.value}
            className={clsx(
              "rounded-md px-2.5 py-1 text-xs font-medium transition-colors",
              value === option.value
                ? "bg-brand-700 text-white"
                : "text-slate-600 hover:bg-slate-100"
            )}
          >
            {option.label}
          </button>
        ))}
      </div>
    </div>
  );
}

function NewTaskPanel({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [title, setTitle] = useState("");
  const [clientId, setClientId] = useState<string | null>(null);
  const [assignedToId, setAssignedToId] = useState("");
  const [dueDate, setDueDate] = useState("");
  const [type, setType] = useState<TaskType>("MANUAL");
  const [error, setError] = useState<string | null>(null);

  const { data: users = [] } = useUsers();
  const createTask = useCreateTask();

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setError(null);
    try {
      await createTask.mutateAsync({
        title: title.trim(),
        clientId,
        assignedToId: assignedToId || null,
        dueDate: dueDate ? new Date(dueDate).toISOString() : null,
        type,
      });
      setTitle("");
      setClientId(null);
      setAssignedToId("");
      setDueDate("");
      setType("MANUAL");
      onClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not create the task");
    }
  };

  return (
    <SlideOverPanel
      open={open}
      onClose={onClose}
      title="New task"
      footer={
        <div className="flex justify-end gap-2">
          <Button variant="secondary" onClick={onClose}>
            Cancel
          </Button>
          <Button
            type="submit"
            form="new-task-form"
            loading={createTask.isPending}
            disabled={title.trim().length === 0}
          >
            Create task
          </Button>
        </div>
      }
    >
      <form id="new-task-form" onSubmit={handleSubmit} className="space-y-4">
        <Field label="Title" htmlFor="new-task-title">
          <input
            id="new-task-title"
            className="input"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            autoFocus
          />
        </Field>

        <Field label="Client" htmlFor="new-task-client" hint="Optional — leave blank for internal work.">
          <SearchableClientSelect id="new-task-client" value={clientId} onChange={setClientId} />
        </Field>

        <Field label="Assign to" htmlFor="new-task-assignee">
          <select
            id="new-task-assignee"
            className="input"
            value={assignedToId}
            onChange={(e) => setAssignedToId(e.target.value)}
          >
            <option value="">Unassigned</option>
            {users.map((user) => (
              <option key={user.id} value={user.id}>
                {user.name}
              </option>
            ))}
          </select>
        </Field>

        <Field label="Due date" htmlFor="new-task-due">
          <input
            id="new-task-due"
            type="date"
            className="input"
            value={dueDate}
            onChange={(e) => setDueDate(e.target.value)}
          />
        </Field>

        <Field label="Type" htmlFor="new-task-type">
          <select
            id="new-task-type"
            className="input"
            value={type}
            onChange={(e) => setType(e.target.value as TaskType)}
          >
            <option value="MANUAL">{TASK_TYPE_LABELS.MANUAL}</option>
            <option value="BUILD_MILESTONE">{TASK_TYPE_LABELS.BUILD_MILESTONE}</option>
            {AUTO_TYPES.map((option) => (
              <option key={option} value={option}>
                {TASK_TYPE_LABELS[option]}
              </option>
            ))}
          </select>
        </Field>

        {error && <p className="text-sm text-red-600">{error}</p>}
      </form>
    </SlideOverPanel>
  );
}
