import { Hono } from "hono";
import { OPEN_TASK_STATUSES } from "../domain/enums";
import { createTaskSchema, updateTaskSchema } from "../utils/validation";
import type { AppEnv } from "../types";

const router = new Hono<AppEnv>();

const TASK_INCLUDE = {
  client: { select: { id: true, businessName: true, currentTier: true } },
  assignedTo: { select: { id: true, name: true, role: true } },
};

router.get("/", async (c) => {
  const { assignedToId, status, clientId, type, dueBefore, includeCompleted } = c.req.query();

  const where: Record<string, unknown> = {};
  if (assignedToId) where.assignedToId = assignedToId;
  if (clientId) where.clientId = clientId;
  if (type) where.type = { in: type.split(",") };
  if (dueBefore) where.dueDate = { lte: new Date(dueBefore) };

  if (status) {
    where.status = { in: status.split(",") };
  } else if (includeCompleted !== "true") {
    where.status = { in: OPEN_TASK_STATUSES };
  }

  const tasks = await c.get("prisma").task.findMany({
    where,
    include: TASK_INCLUDE,
    orderBy: [{ dueDate: { sort: "asc", nulls: "last" } }, { createdAt: "desc" }],
  });
  return c.json(tasks);
});

router.post("/", async (c) => {
  const parsed = createTaskSchema.safeParse(await c.req.json().catch(() => null));
  if (!parsed.success) return c.json({ error: parsed.error.flatten() }, 400);

  const task = await c.get("prisma").task.create({
    data: { ...parsed.data, autoGenerated: false },
    include: TASK_INCLUDE,
  });
  return c.json(task, 201);
});

router.patch("/:id", async (c) => {
  const parsed = updateTaskSchema.safeParse(await c.req.json().catch(() => null));
  if (!parsed.success) return c.json({ error: parsed.error.flatten() }, 400);

  const data: Record<string, unknown> = { ...parsed.data };

  // Keep completedAt in step with status so "done" always has a timestamp
  // and re-opening a task clears the old one.
  if (parsed.data.status === "DONE") data.completedAt = new Date();
  if (parsed.data.status && parsed.data.status !== "DONE") data.completedAt = null;
  if (parsed.data.snoozedUntil) data.status = "SNOOZED";

  const task = await c.get("prisma").task.update({
    where: { id: c.req.param("id") },
    data,
    include: TASK_INCLUDE,
  });
  return c.json(task);
});

router.post("/:id/complete", async (c) => {
  const task = await c.get("prisma").task.update({
    where: { id: c.req.param("id") },
    data: { status: "DONE", completedAt: new Date() },
    include: TASK_INCLUDE,
  });
  return c.json(task);
});

router.delete("/:id", async (c) => {
  await c.get("prisma").task.delete({ where: { id: c.req.param("id") } });
  return c.body(null, 204);
});

export default router;
