import { Router } from "express";
import { Prisma, TaskStatus } from "@prisma/client";
import { prisma } from "../config/db";
import { asyncHandler } from "../middleware/errorHandler";
import { createTaskSchema, updateTaskSchema } from "../utils/validation";

const router = Router();

const TASK_INCLUDE = {
  client: { select: { id: true, businessName: true, currentTier: true } },
  assignedTo: { select: { id: true, name: true, role: true } },
} satisfies Prisma.TaskInclude;

const OPEN_STATUSES: TaskStatus[] = ["OPEN", "IN_PROGRESS", "SNOOZED"];

router.get(
  "/",
  asyncHandler(async (req, res) => {
    const { assignedToId, status, clientId, type, dueBefore, includeCompleted } = req.query;

    const where: Prisma.TaskWhereInput = {};
    if (assignedToId) where.assignedToId = String(assignedToId);
    if (clientId) where.clientId = String(clientId);
    if (type) where.type = { in: String(type).split(",") as never };
    if (dueBefore) where.dueDate = { lte: new Date(String(dueBefore)) };

    if (status) {
      where.status = { in: String(status).split(",") as never };
    } else if (includeCompleted !== "true") {
      where.status = { in: OPEN_STATUSES };
    }

    const tasks = await prisma.task.findMany({
      where,
      include: TASK_INCLUDE,
      orderBy: [{ dueDate: { sort: "asc", nulls: "last" } }, { createdAt: "desc" }],
    });
    res.json(tasks);
  })
);

router.post(
  "/",
  asyncHandler(async (req, res) => {
    const parsed = createTaskSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.flatten() });

    const task = await prisma.task.create({
      data: { ...parsed.data, autoGenerated: false },
      include: TASK_INCLUDE,
    });
    res.status(201).json(task);
  })
);

router.patch(
  "/:id",
  asyncHandler(async (req, res) => {
    const parsed = updateTaskSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.flatten() });

    const data: Prisma.TaskUpdateInput = { ...parsed.data } as Prisma.TaskUpdateInput;

    // Keep completedAt in step with status so "done" always has a timestamp
    // and re-opening a task clears the old one.
    if (parsed.data.status === "DONE") data.completedAt = new Date();
    if (parsed.data.status && parsed.data.status !== "DONE") data.completedAt = null;
    if (parsed.data.snoozedUntil) data.status = "SNOOZED";

    const task = await prisma.task.update({
      where: { id: req.params.id },
      data,
      include: TASK_INCLUDE,
    });
    res.json(task);
  })
);

router.post(
  "/:id/complete",
  asyncHandler(async (req, res) => {
    const task = await prisma.task.update({
      where: { id: req.params.id },
      data: { status: "DONE", completedAt: new Date() },
      include: TASK_INCLUDE,
    });
    res.json(task);
  })
);

router.delete(
  "/:id",
  asyncHandler(async (req, res) => {
    await prisma.task.delete({ where: { id: req.params.id } });
    res.status(204).send();
  })
);

export default router;
