import type { PrismaClient } from "../generated/prisma/client";
import { OPEN_TASK_STATUSES, type ServiceTierType } from "../domain/enums";

/**
 * The one write path allowed to change `Client.currentTier`.
 *
 * A tier change is consequential: it resets every automation timer hanging off
 * that client, so it always (a) writes an audit row, (b) backfills
 * `websiteLaunchDate` the first time a site goes live, and (c) retires the
 * upsell tasks that belonged to the tier we just left.
 *
 * ---
 * D1 caveat: Cloudflare D1 has no transaction support, and Prisma's D1 adapter
 * runs `$transaction` as individual queries (https://pris.ly/d/d1-transactions).
 * The Postgres version wrapped these three writes in one atomic transaction; we
 * cannot, so instead they are *ordered by failure consequence* — every partial
 * outcome is visible in the UI and self-corrects rather than silently rotting:
 *
 *   1. audit row     — if a later step fails, the history row is one cosmetic
 *                      extra line and the tier visibly did not change, so the
 *                      user simply retries.
 *   2. tier update   — if the last step fails, stale nags stay open where
 *                      somebody can see and close them.
 *   3. retire nags   — last, because it is the only step whose failure leaves
 *                      no incorrect state, just un-tidied state.
 *
 * Nothing here can leave a changed `currentTier` with no audit row, which is the
 * one combination that would quietly break the automation engine's anchors.
 */
export async function updateClientTier(
  prisma: PrismaClient,
  clientId: string,
  newTier: ServiceTierType,
  userId: string | null,
  note?: string | null
) {
  const client = await prisma.client.findUniqueOrThrow({ where: { id: clientId } });

  if (client.currentTier === newTier) {
    return client;
  }

  const previousTier = client.currentTier;

  await prisma.serviceHistoryEntry.create({
    data: {
      clientId,
      fromTier: previousTier,
      toTier: newTier,
      changedById: userId,
      note: note ?? null,
    },
  });

  const updateData: { currentTier: ServiceTierType; websiteLaunchDate?: Date } = {
    currentTier: newTier,
  };
  if (newTier === "WEBSITE_LIVE" && !client.websiteLaunchDate) {
    updateData.websiteLaunchDate = new Date();
  }

  const updated = await prisma.client.update({
    where: { id: clientId },
    data: updateData,
  });

  // Retire the upsell nags that belonged to the tier we just left. Scoped to
  // that tier's rules on purpose: recurring check-ins and contract-renewal
  // reminders survive a tier change, because they're still relevant.
  const staleRules = await prisma.automationRule.findMany({
    where: { triggerTier: previousTier },
    select: { id: true },
  });

  if (staleRules.length > 0) {
    await prisma.task.updateMany({
      where: {
        clientId,
        autoGenerated: true,
        status: { in: OPEN_TASK_STATUSES },
        sourceRuleId: { in: staleRules.map((r) => r.id) },
      },
      data: { status: "CANCELLED" },
    });
  }

  return updated;
}

export const CLIENT_DETAIL_INCLUDE = {
  contacts: { orderBy: [{ isPrimary: "desc" as const }, { lastName: "asc" as const }] },
  retainers: { orderBy: { createdAt: "desc" as const } },
  tasks: {
    orderBy: [{ status: "asc" as const }, { dueDate: "asc" as const }],
    include: { assignedTo: { select: { id: true, name: true, role: true } } },
  },
  interactions: {
    orderBy: { occurredAt: "desc" as const },
    include: { loggedBy: { select: { id: true, name: true } } },
  },
  serviceHistory: {
    orderBy: { changedAt: "desc" as const },
    include: { changedBy: { select: { id: true, name: true } } },
  },
  documents: { orderBy: { uploadedAt: "desc" as const } },
  accountOwner: { select: { id: true, name: true, role: true } },
};
