import { Prisma, ServiceTierType } from "@prisma/client";
import { prisma } from "../config/db";

/**
 * The one write path allowed to change `Client.currentTier`.
 *
 * A tier change is consequential: it resets every automation timer hanging off
 * that client, so it always (a) writes an audit row, (b) backfills
 * `websiteLaunchDate` the first time a site goes live, and (c) retires the
 * upsell tasks that belonged to the tier we just left.
 */
export async function updateClientTier(
  clientId: string,
  newTier: ServiceTierType,
  userId: string | null,
  note?: string | null
) {
  return prisma.$transaction(async (tx) => {
    const client = await tx.client.findUniqueOrThrow({ where: { id: clientId } });

    if (client.currentTier === newTier) {
      return client;
    }

    const previousTier = client.currentTier;

    await tx.serviceHistoryEntry.create({
      data: {
        clientId,
        fromTier: previousTier,
        toTier: newTier,
        changedById: userId,
        note: note ?? null,
      },
    });

    const updateData: { currentTier: ServiceTierType; websiteLaunchDate?: Date } = {
      currentTier: newTier,
    };
    if (newTier === "WEBSITE_LIVE" && !client.websiteLaunchDate) {
      updateData.websiteLaunchDate = new Date();
    }

    const updated = await tx.client.update({
      where: { id: clientId },
      data: updateData,
    });

    // Retire the upsell nags that belonged to the tier we just left. Scoped to
    // that tier's rules on purpose: recurring check-ins and contract-renewal
    // reminders survive a tier change, because they're still relevant.
    const staleRules = await tx.automationRule.findMany({
      where: { triggerTier: previousTier },
      select: { id: true },
    });

    if (staleRules.length > 0) {
      await tx.task.updateMany({
        where: {
          clientId,
          autoGenerated: true,
          status: { in: ["OPEN", "SNOOZED", "IN_PROGRESS"] },
          sourceRuleId: { in: staleRules.map((r) => r.id) },
        },
        data: { status: "CANCELLED" },
      });
    }

    return updated;
  });
}

export const CLIENT_DETAIL_INCLUDE = {
  contacts: { orderBy: [{ isPrimary: "desc" }, { lastName: "asc" }] },
  retainers: { orderBy: { createdAt: "desc" } },
  tasks: {
    orderBy: [{ status: "asc" }, { dueDate: "asc" }],
    include: { assignedTo: { select: { id: true, name: true, role: true } } },
  },
  interactions: {
    orderBy: { occurredAt: "desc" },
    include: { loggedBy: { select: { id: true, name: true } } },
  },
  serviceHistory: {
    orderBy: { changedAt: "desc" },
    include: { changedBy: { select: { id: true, name: true } } },
  },
  documents: { orderBy: { uploadedAt: "desc" } },
  accountOwner: { select: { id: true, name: true, role: true } },
} satisfies Prisma.ClientInclude;
