import { useEffect, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { interactionsApi, tasksApi } from "../api/resources";
import type { InteractionType, Task } from "../types";
import { INTERACTION_LABELS } from "../lib/format";
import { ConfirmModal } from "./ConfirmModal";

const INTERACTION_OPTIONS: InteractionType[] = [
  "CALL",
  "EMAIL",
  "MEETING",
  "TEXT",
  "SITE_VISIT",
  "OTHER",
];

interface PitchNowModalProps {
  open: boolean;
  clientId: string | null;
  businessName: string;
  onClose: () => void;
}

/**
 * One click from the at-risk panel: log what was said and close out the upsell
 * task the automation engine raised. The whole point is that recording a pitch
 * takes seconds, so it actually gets recorded.
 */
export function PitchNowModal({ open, clientId, businessName, onClose }: PitchNowModalProps) {
  const [type, setType] = useState<InteractionType>("CALL");
  const [summary, setSummary] = useState("");
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const queryClient = useQueryClient();

  useEffect(() => {
    if (open) {
      setType("CALL");
      setSummary("");
      setError(null);
    }
  }, [open, clientId]);

  const handleConfirm = async () => {
    if (!clientId || summary.trim().length === 0) return;
    setSaving(true);
    setError(null);

    try {
      await interactionsApi.create(clientId, { type, summary: summary.trim() });

      // Close out whichever upsell nag prompted this pitch.
      const openTasks = await tasksApi.list({ clientId, status: "OPEN,IN_PROGRESS,SNOOZED" });
      const pitchTasks = openTasks.filter(
        (t: Task) => t.autoGenerated && t.type === "AUTO_UPSELL_PITCH"
      );
      await Promise.all(pitchTasks.map((t) => tasksApi.complete(t.id)));

      queryClient.invalidateQueries();
      onClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not save the pitch");
    } finally {
      setSaving(false);
    }
  };

  return (
    <ConfirmModal
      open={open}
      title={`Log a pitch to ${businessName}`}
      tone="warning"
      confirmLabel="Log pitch & close task"
      loading={saving}
      confirmDisabled={summary.trim().length === 0}
      onConfirm={handleConfirm}
      onCancel={onClose}
      body={
        <div className="space-y-3">
          <div>
            <label className="label" htmlFor="pitch-type">
              How did you reach them?
            </label>
            <select
              id="pitch-type"
              className="input"
              value={type}
              onChange={(e) => setType(e.target.value as InteractionType)}
            >
              {INTERACTION_OPTIONS.map((option) => (
                <option key={option} value={option}>
                  {INTERACTION_LABELS[option]}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="label" htmlFor="pitch-summary">
              What happened?
            </label>
            <textarea
              id="pitch-summary"
              className="input min-h-[90px]"
              placeholder="Pitched brand curation at $600/mo. Wants to think it over until Friday."
              value={summary}
              onChange={(e) => setSummary(e.target.value)}
              autoFocus
            />
          </div>

          <p className="text-xs text-slate-500">
            This logs the interaction and marks any open upsell task for {businessName} as done.
          </p>

          {error && <p className="text-xs text-red-600">{error}</p>}
        </div>
      }
    />
  );
}
