import clsx from "clsx";
import { Link } from "react-router-dom";
import { Bot, Clock } from "lucide-react";
import type { Task } from "../types";
import { formatRelative, isOverdue, TASK_TYPE_LABELS } from "../lib/format";

interface TaskChecklistItemProps {
  task: Task;
  onComplete: (taskId: string) => void;
  onSnooze?: (taskId: string) => void;
  showClient?: boolean;
  disabled?: boolean;
}

export function TaskChecklistItem({
  task,
  onComplete,
  onSnooze,
  showClient = true,
  disabled = false,
}: TaskChecklistItemProps) {
  const done = task.status === "DONE";
  const overdue = !done && isOverdue(task.dueDate);

  return (
    <li
      className={clsx(
        "group flex items-start gap-3 rounded-lg border px-3 py-2.5 transition-all",
        done
          ? "border-separator/70 bg-fill/8 opacity-60"
          : overdue
            ? "border-danger/30 bg-danger/8"
            : "border-separator/70 bg-content hover:border-separator"
      )}
    >
      {/* The box stays visually small, but the label around it is a 44px target
          on touch — completing a task is the single most-tapped action here.
          Negative margins keep the row the same height as before. */}
      <label
        className="-my-1.5 -ml-1.5 flex h-11 w-11 shrink-0 cursor-pointer items-center justify-center
                   lg:-my-0 lg:-ml-0 lg:mt-0.5 lg:h-4 lg:w-4"
      >
        <input
          type="checkbox"
          checked={done}
          disabled={disabled || done}
          onChange={() => onComplete(task.id)}
          aria-label={`Mark "${task.title}" done`}
          className="h-5 w-5 cursor-pointer rounded border-separator text-accent
                     focus:ring-brand-500 disabled:cursor-default lg:h-4 lg:w-4"
        />
      </label>

      <div className="min-w-0 flex-1">
        <div className="flex items-start gap-1.5">
          {task.autoGenerated && (
            <Bot
              className="mt-0.5 h-3.5 w-3.5 shrink-0 text-accent"
              aria-label="Generated automatically"
            />
          )}
          <p
            className={clsx(
              "text-sm leading-snug",
              done ? "text-ink/65 line-through" : "font-medium text-ink"
            )}
          >
            {task.title}
          </p>
        </div>

        <div className="mt-1 flex flex-wrap items-center gap-x-2 gap-y-1 text-xs">
          {showClient && task.client && (
            <Link
              to={`/clients/${task.client.id}`}
              className="rounded-full bg-fill/15 px-2 py-0.5 font-medium text-ink/70 hover:bg-fill/25"
            >
              {task.client.businessName}
            </Link>
          )}
          {task.dueDate && (
            <span className={overdue ? "font-medium text-danger" : "text-ink/70"}>
              {formatRelative(task.dueDate)}
            </span>
          )}
          {task.assignedTo && <span className="text-ink/65">{task.assignedTo.name}</span>}
          {task.type !== "MANUAL" && (
            <span className="text-ink/65">{TASK_TYPE_LABELS[task.type]}</span>
          )}
        </div>
      </div>

      {onSnooze && !done && (
        <button
          type="button"
          onClick={() => onSnooze(task.id)}
          title="Snooze one week"
          aria-label={`Snooze "${task.title}" one week`}
          // Reveal-on-hover hid this button completely on touch, where there is
          // no hover to trigger it — so snoozing was desktop-only. It now stays
          // visible by default and only hides behind hover where hover exists.
          className="-my-1.5 -mr-1.5 flex h-11 w-11 shrink-0 items-center justify-center rounded
                     text-ink/55 transition-opacity hover:bg-fill/15 hover:text-ink/70
                     lg:-my-0 lg:-mr-0 lg:h-8 lg:w-8
                     [@media(any-hover:hover)]:opacity-0
                     [@media(any-hover:hover)]:focus-visible:opacity-100
                     [@media(any-hover:hover)]:group-hover:opacity-100"
        >
          <Clock className="h-4 w-4" aria-hidden />
        </button>
      )}
    </li>
  );
}
