import clsx from "clsx";
import { Link } from "react-router-dom";
import { Bot, Clock } from "lucide-react";
import type { Task } from "../types";
import { formatRelative, isOverdue, TASK_TYPE_LABELS } from "../lib/format";

interface TaskChecklistItemProps {
  task: Task;
  onComplete: (taskId: string) => void;
  onSnooze?: (taskId: string) => void;
  showClient?: boolean;
  disabled?: boolean;
}

export function TaskChecklistItem({
  task,
  onComplete,
  onSnooze,
  showClient = true,
  disabled = false,
}: TaskChecklistItemProps) {
  const done = task.status === "DONE";
  const overdue = !done && isOverdue(task.dueDate);

  return (
    <li
      className={clsx(
        "group flex items-start gap-3 rounded-lg border px-3 py-2.5 transition-all",
        done
          ? "border-slate-200 bg-slate-50 opacity-60"
          : overdue
            ? "border-red-200 bg-red-50/50"
            : "border-slate-200 bg-white hover:border-slate-300"
      )}
    >
      <input
        type="checkbox"
        checked={done}
        disabled={disabled || done}
        onChange={() => onComplete(task.id)}
        aria-label={`Mark "${task.title}" done`}
        className="mt-0.5 h-4 w-4 shrink-0 cursor-pointer rounded border-slate-300 text-brand-700
                   focus:ring-brand-500 disabled:cursor-default"
      />

      <div className="min-w-0 flex-1">
        <div className="flex items-start gap-1.5">
          {task.autoGenerated && (
            <Bot
              className="mt-0.5 h-3.5 w-3.5 shrink-0 text-brand-500"
              aria-label="Generated automatically"
            />
          )}
          <p
            className={clsx(
              "text-sm leading-snug",
              done ? "text-slate-400 line-through" : "font-medium text-slate-900"
            )}
          >
            {task.title}
          </p>
        </div>

        <div className="mt-1 flex flex-wrap items-center gap-x-2 gap-y-1 text-xs">
          {showClient && task.client && (
            <Link
              to={`/clients/${task.client.id}`}
              className="rounded-full bg-slate-100 px-2 py-0.5 font-medium text-slate-600 hover:bg-slate-200"
            >
              {task.client.businessName}
            </Link>
          )}
          {task.dueDate && (
            <span className={overdue ? "font-medium text-red-600" : "text-slate-500"}>
              {formatRelative(task.dueDate)}
            </span>
          )}
          {task.assignedTo && <span className="text-slate-400">{task.assignedTo.name}</span>}
          {task.type !== "MANUAL" && (
            <span className="text-slate-400">{TASK_TYPE_LABELS[task.type]}</span>
          )}
        </div>
      </div>

      {onSnooze && !done && (
        <button
          type="button"
          onClick={() => onSnooze(task.id)}
          title="Snooze one week"
          aria-label={`Snooze "${task.title}" one week`}
          className="shrink-0 rounded p-1 text-slate-300 opacity-0 transition-opacity hover:bg-slate-100
                     hover:text-slate-600 focus-visible:opacity-100 group-hover:opacity-100"
        >
          <Clock className="h-4 w-4" />
        </button>
      )}
    </li>
  );
}
