import cron from "node-cron";
import { AutomationRule, Client, Retainer, ServiceTierType, Task } from "@prisma/client";
import { prisma } from "../config/db";
import { env } from "../config/env";
import { sendTaskNotificationEmail } from "../services/emailService";
import { addDays, daysBetween, startOfDay } from "../utils/dateHelpers";

type ClientWithRelations = Client & { retainers: Retainer[]; tasks: Task[] };

export interface AutomationRunResult {
  ranAt: Date;
  clientsChecked: number;
  rulesChecked: number;
  tasksCreated: { taskId: string; clientId: string; ruleId: string; title: string }[];
}

/**
 * Runs daily. Checks every active client against every active automation rule and
 * creates the task the moment the rule's countdown is up — this is what stops a
 * client from quietly sitting at WEBSITE_LIVE forever with nobody pitching them.
 *
 * Idempotent by design: a rule that already has a live task for a client is
 * skipped, so re-running the job on the same day creates nothing new.
 */
export async function runAutomationEngine(now = new Date()): Promise<AutomationRunResult> {
  const rules = await prisma.automationRule.findMany({ where: { isActive: true } });
  const clients = await prisma.client.findMany({
    where: { isActive: true },
    include: { retainers: true, tasks: true },
  });

  const result: AutomationRunResult = {
    ranAt: now,
    clientsChecked: clients.length,
    rulesChecked: rules.length,
    tasksCreated: [],
  };

  for (const client of clients) {
    for (const rule of rules) {
      const created = await evaluateRule(client, rule, now);
      if (created) {
        result.tasksCreated.push({
          taskId: created.id,
          clientId: client.id,
          ruleId: rule.id,
          title: created.title,
        });
      }
    }
  }

  console.log(
    `[automation] checked ${result.clientsChecked} clients x ${result.rulesChecked} rules, created ${result.tasksCreated.length} task(s)`
  );
  return result;
}

async function evaluateRule(
  client: ClientWithRelations,
  rule: AutomationRule,
  now: Date
): Promise<Task | null> {
  // A null triggerTier means "any tier" — used by the retainer-anchored rules.
  if (rule.triggerTier && client.currentTier !== rule.triggerTier) return null;
  if (rule.requiresActiveRetainer && !client.retainers.some((r) => r.status === "ACTIVE")) {
    return null;
  }

  const liveTasksFromRule = client.tasks.filter(
    (t) => t.sourceRuleId === rule.id && ["OPEN", "IN_PROGRESS", "SNOOZED"].includes(t.status)
  );
  // Never stack a second copy of a nag on top of one that's still open.
  if (liveTasksFromRule.length > 0) return null;

  const anchorDate = await getAnchorDate(client, rule);
  if (!anchorDate) return null;

  // Recurring rules (quarterly check-in) count from the last task they produced,
  // so the clock restarts each cycle instead of firing forever off one anchor.
  const effectiveAnchor = rule.repeatEveryDays
    ? latestTaskDateFromRule(client, rule.id) ?? anchorDate
    : anchorDate;
  const threshold = rule.repeatEveryDays
    ? rule.repeatEveryDays
    : rule.daysAfterTrigger;

  const daysSinceAnchor = daysBetween(effectiveAnchor, now);
  if (daysSinceAnchor < threshold) return null;

  const title = renderTemplate(rule.taskTitleTemplate, client, rule.triggerTier);

  const assignedToId = await resolveAssignee(client, rule);

  const newTask = await prisma.task.create({
    data: {
      clientId: client.id,
      title,
      description: `Generated automatically by the "${rule.name}" rule.`,
      type: rule.taskType,
      autoGenerated: true,
      sourceRuleId: rule.id,
      dueDate: startOfDay(now),
      assignedToId,
    },
  });

  const assignee = assignedToId
    ? await prisma.user.findUnique({ where: { id: assignedToId } })
    : null;
  await sendTaskNotificationEmail(newTask, client, assignee);

  return newTask;
}

/**
 * Which date the rule counts from.
 *  - WEBSITE_LIVE tier rules anchor on websiteLaunchDate (falling back to the
 *    history row, for clients whose launch date was never filled in).
 *  - Other tier rules anchor on the most recent move into that tier.
 *  - Retainer rules anchor on the retainer's start or end date.
 */
async function getAnchorDate(
  client: ClientWithRelations,
  rule: AutomationRule
): Promise<Date | null> {
  if (rule.anchor === "RETAINER_START") {
    const active = client.retainers
      .filter((r) => r.status === "ACTIVE" && r.startDate)
      .sort((a, b) => a.startDate!.getTime() - b.startDate!.getTime())[0];
    return active?.startDate ?? null;
  }

  if (rule.anchor === "RETAINER_END") {
    // daysAfterTrigger is negative for these ("14 days before expiry"), so the
    // effective anchor is the end date shifted backwards by that many days.
    const expiring = client.retainers
      .filter((r) => r.endDate && ["ACTIVE", "PENDING_FIRST_PAYMENT"].includes(r.status))
      .sort((a, b) => a.endDate!.getTime() - b.endDate!.getTime())[0];
    if (!expiring?.endDate) return null;
    return addDays(expiring.endDate, rule.daysAfterTrigger);
  }

  if (rule.triggerTier === "WEBSITE_LIVE" && client.websiteLaunchDate) {
    return client.websiteLaunchDate;
  }

  const tier = rule.triggerTier ?? client.currentTier;
  const historyEntry = await prisma.serviceHistoryEntry.findFirst({
    where: { clientId: client.id, toTier: tier },
    orderBy: { changedAt: "desc" },
  });
  return historyEntry?.changedAt ?? null;
}

function latestTaskDateFromRule(client: ClientWithRelations, ruleId: string): Date | null {
  const fromRule = client.tasks
    .filter((t) => t.sourceRuleId === ruleId)
    .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
  return fromRule[0]?.createdAt ?? null;
}

/** Sales nags go to the account owner; build work goes to the technical user. */
async function resolveAssignee(
  client: ClientWithRelations,
  rule: AutomationRule
): Promise<string | null> {
  if (rule.taskType === "BUILD_MILESTONE") {
    const technical = await prisma.user.findFirst({ where: { role: "TECHNICAL" } });
    if (technical) return technical.id;
  }
  if (client.accountOwnerId) return client.accountOwnerId;
  const sales = await prisma.user.findFirst({ where: { role: "SALES" } });
  return sales?.id ?? null;
}

const TIER_LABELS: Record<ServiceTierType, string> = {
  PROSPECT: "Prospect",
  WEBSITE_BUILD: "Website Build",
  WEBSITE_LIVE: "Website Live",
  BRAND_CURATION: "Brand Curation",
  SOCIAL_MEDIA: "Social Media",
  ANALYTICS: "Analytics",
  CHURNED: "Churned",
};

export function renderTemplate(
  template: string,
  client: Pick<Client, "businessName" | "currentTier">,
  triggerTier: ServiceTierType | null
): string {
  const tier = triggerTier ?? client.currentTier;
  return template
    .replace(/\{\{businessName\}\}/g, client.businessName)
    .replace(/\{\{tier\}\}/g, TIER_LABELS[tier]);
}

let scheduled: cron.ScheduledTask | null = null;

export function startAutomationCron() {
  if (env.DISABLE_CRON) {
    console.log("[automation] cron disabled via DISABLE_CRON");
    return;
  }
  if (scheduled) return;

  scheduled = cron.schedule(env.AUTOMATION_CRON, () => {
    runAutomationEngine().catch((err) => console.error("Automation engine failed:", err));
  });
  console.log(`[automation] scheduled with cron expression "${env.AUTOMATION_CRON}"`);
}
