import type { PrismaClient } from "../generated/prisma/client";
import {
  OPEN_TASK_STATUSES,
  TIER_LABELS,
  type ServiceTierType,
  type TaskType,
} from "../domain/enums";
import { sendTaskNotificationEmail } from "../services/emailService";
import { addDays, daysBetween, startOfDay } from "../utils/dateHelpers";

export interface AutomationRunResult {
  ranAt: Date;
  clientsChecked: number;
  rulesChecked: number;
  tasksCreated: { taskId: string; clientId: string; ruleId: string; title: string }[];
}

type Rule = {
  id: string;
  name: string;
  triggerTier: string | null;
  anchor: string;
  daysAfterTrigger: number;
  repeatEveryDays: number | null;
  requiresActiveRetainer: boolean;
  taskTitleTemplate: string;
  taskType: string;
};

type Retainer = { status: string; startDate: Date | null; endDate: Date | null };
type Task = { id: string; sourceRuleId: string | null; status: string; createdAt: Date };
type ClientRow = {
  id: string;
  businessName: string;
  currentTier: string;
  websiteLaunchDate: Date | null;
  accountOwnerId: string | null;
  retainers: Retainer[];
  tasks: Task[];
};

/**
 * Runs daily on a Cloudflare Cron Trigger. Checks every active client against
 * every active automation rule and creates the task the moment the rule's
 * countdown is up — this is what stops a client from quietly sitting at
 * WEBSITE_LIVE forever with nobody pitching them.
 *
 * Idempotent by design: a rule that already has a live task for a client is
 * skipped, so re-running the job on the same day creates nothing new.
 *
 * Everything the rules need is loaded up front. The Node version queried the
 * service-history table once per client × rule; on D1 each query is a real round
 * trip and Workers cap the subrequests a single invocation may make, so the same
 * work is done from three bulk reads instead of O(clients × rules) of them.
 */
export async function runAutomationEngine(
  prisma: PrismaClient,
  env: Env,
  now = new Date()
): Promise<AutomationRunResult> {
  const [rules, clients, users] = await Promise.all([
    prisma.automationRule.findMany({ where: { isActive: true } }),
    prisma.client.findMany({
      where: { isActive: true },
      include: { retainers: true, tasks: true },
    }),
    prisma.user.findMany({ select: { id: true, name: true, email: true, role: true } }),
  ]);

  const history = await prisma.serviceHistoryEntry.findMany({
    where: { clientId: { in: clients.map((c) => c.id) } },
    orderBy: { changedAt: "desc" },
    select: { clientId: true, toTier: true, changedAt: true },
  });

  // Latest move into each (client, tier) pair — the anchor for tier-based rules.
  const latestTierChange = new Map<string, Date>();
  for (const entry of history) {
    const key = `${entry.clientId}:${entry.toTier}`;
    if (!latestTierChange.has(key)) latestTierChange.set(key, entry.changedAt);
  }

  const technicalUser = users.find((u) => u.role === "TECHNICAL") ?? null;
  const salesUser = users.find((u) => u.role === "SALES") ?? null;
  const usersById = new Map(users.map((u) => [u.id, u]));

  const result: AutomationRunResult = {
    ranAt: now,
    clientsChecked: clients.length,
    rulesChecked: rules.length,
    tasksCreated: [],
  };

  for (const client of clients) {
    for (const rule of rules) {
      const plan = planTask(client as ClientRow, rule as Rule, latestTierChange, now);
      if (!plan) continue;

      const assignedToId = resolveAssignee(
        client as ClientRow,
        rule as Rule,
        technicalUser,
        salesUser
      );

      const newTask = await prisma.task.create({
        data: {
          clientId: client.id,
          title: plan.title,
          description: `Generated automatically by the "${rule.name}" rule.`,
          type: rule.taskType,
          autoGenerated: true,
          sourceRuleId: rule.id,
          dueDate: startOfDay(now),
          assignedToId,
        },
      });

      const assignee = assignedToId ? usersById.get(assignedToId) ?? null : null;
      await sendTaskNotificationEmail(env, newTask, client, assignee);

      result.tasksCreated.push({
        taskId: newTask.id,
        clientId: client.id,
        ruleId: rule.id,
        title: newTask.title,
      });
    }
  }

  console.log(
    `[automation] checked ${result.clientsChecked} clients x ${result.rulesChecked} rules, created ${result.tasksCreated.length} task(s)`
  );
  return result;
}

/** Decides whether a rule is due for a client, and what the task would be called. */
function planTask(
  client: ClientRow,
  rule: Rule,
  latestTierChange: Map<string, Date>,
  now: Date
): { title: string } | null {
  // A null triggerTier means "any tier" — used by the retainer-anchored rules.
  if (rule.triggerTier && client.currentTier !== rule.triggerTier) return null;
  if (rule.requiresActiveRetainer && !client.retainers.some((r) => r.status === "ACTIVE")) {
    return null;
  }

  const liveTasksFromRule = client.tasks.filter(
    (t) => t.sourceRuleId === rule.id && OPEN_TASK_STATUSES.includes(t.status as never)
  );
  // Never stack a second copy of a nag on top of one that's still open.
  if (liveTasksFromRule.length > 0) return null;

  const anchorDate = getAnchorDate(client, rule, latestTierChange);
  if (!anchorDate) return null;

  // Recurring rules (quarterly check-in) count from the last task they produced,
  // so the clock restarts each cycle instead of firing forever off one anchor.
  const effectiveAnchor = rule.repeatEveryDays
    ? latestTaskDateFromRule(client, rule.id) ?? anchorDate
    : anchorDate;
  const threshold = rule.repeatEveryDays ? rule.repeatEveryDays : rule.daysAfterTrigger;

  if (daysBetween(effectiveAnchor, now) < threshold) return null;

  return { title: renderTemplate(rule.taskTitleTemplate, client, rule.triggerTier) };
}

/**
 * Which date the rule counts from.
 *  - WEBSITE_LIVE tier rules anchor on websiteLaunchDate (falling back to the
 *    history row, for clients whose launch date was never filled in).
 *  - Other tier rules anchor on the most recent move into that tier.
 *  - Retainer rules anchor on the retainer's start or end date.
 */
function getAnchorDate(
  client: ClientRow,
  rule: Rule,
  latestTierChange: Map<string, Date>
): Date | null {
  if (rule.anchor === "RETAINER_START") {
    const active = client.retainers
      .filter((r) => r.status === "ACTIVE" && r.startDate)
      .sort((a, b) => a.startDate!.getTime() - b.startDate!.getTime())[0];
    return active?.startDate ?? null;
  }

  if (rule.anchor === "RETAINER_END") {
    // daysAfterTrigger is negative for these ("14 days before expiry"), so the
    // effective anchor is the end date shifted backwards by that many days.
    const expiring = client.retainers
      .filter((r) => r.endDate && ["ACTIVE", "PENDING_FIRST_PAYMENT"].includes(r.status))
      .sort((a, b) => a.endDate!.getTime() - b.endDate!.getTime())[0];
    if (!expiring?.endDate) return null;
    return addDays(expiring.endDate, rule.daysAfterTrigger);
  }

  if (rule.triggerTier === "WEBSITE_LIVE" && client.websiteLaunchDate) {
    return client.websiteLaunchDate;
  }

  const tier = rule.triggerTier ?? client.currentTier;
  return latestTierChange.get(`${client.id}:${tier}`) ?? null;
}

function latestTaskDateFromRule(client: ClientRow, ruleId: string): Date | null {
  const fromRule = client.tasks
    .filter((t) => t.sourceRuleId === ruleId)
    .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
  return fromRule[0]?.createdAt ?? null;
}

/** Sales nags go to the account owner; build work goes to the technical user. */
function resolveAssignee(
  client: ClientRow,
  rule: Rule,
  technicalUser: { id: string } | null,
  salesUser: { id: string } | null
): string | null {
  if (rule.taskType === ("BUILD_MILESTONE" satisfies TaskType) && technicalUser) {
    return technicalUser.id;
  }
  if (client.accountOwnerId) return client.accountOwnerId;
  return salesUser?.id ?? null;
}

export function renderTemplate(
  template: string,
  client: { businessName: string; currentTier: string },
  triggerTier: string | null
): string {
  const tier = (triggerTier ?? client.currentTier) as ServiceTierType;
  return template
    .replace(/\{\{businessName\}\}/g, client.businessName)
    .replace(/\{\{tier\}\}/g, TIER_LABELS[tier] ?? tier);
}
